// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD37wnxPwowcVyeojhuOcjR6fYnZVdYT0',
    appId: '1:267787458859:android:be2f205350d0a9186bcd6e',
    messagingSenderId: '267787458859',
    projectId: 'social-app-325a7',
    storageBucket: 'social-app-325a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHYGaKRt_yBP_onrm8z6yMsFWBg4yboM0',
    appId: '1:267787458859:ios:ce5d3b6bcc86111c6bcd6e',
    messagingSenderId: '267787458859',
    projectId: 'social-app-325a7',
    storageBucket: 'social-app-325a7.appspot.com',
    androidClientId: '267787458859-1app8ufe383mb6gpb8oh1l0hc2256636.apps.googleusercontent.com',
    iosClientId: '267787458859-c5p21i3i66s7lsuvl9f47nm95ac6a44q.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMedia',
  );
}
